### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by balupton** [devmetal/laren#4]
- [x] seems projectz is used by your npm scripts, but none of the projectz html comments are being used https://github.com/bevry/projectz#readme-files
- [x] you can add `es2015` to your `.gitignore` file and remove it from git, as it is only needed by the published package and not the git repo, here is our [`.gitignore` file](https://github.com/bevry/base/blob/master/.gitignore)

**Comment by devmetal** [comment]
Thank you :) I will fix this issues :)

**Comment by devmetal** [comment]
Thank you again for help :)
